### ISSUE TITLE
Not working on 0.7.2

### ISSUE THREAD

**Issue by TTFH** [metarmask/teardown#12]
When you open the tool, it shows a white screen with the text "Parsing error." and no error on the console.

**Comment by metarmask** [comment]
Cannot reproduce. Could this be #1?

**Comment by TTFH** [comment]
> 
> 
> Cannot reproduce. Could this be #1?

The tool was working, then I updated Teardown to 0.7.2 (non experimental) and the tool shows "Parsing error."
I just downloaded the last commit, compiled it and still not working.

**Comment by TTFH** [comment]
The error was caused by: `let steam_app = find_steam_app("1167630")?;`
I set the folder path manually and now it works.
