### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by Smart-Fella** [metarmask/teardown#18]
When I try and decompile a map, I get an error depending on the version I use.

0.9.0:
`Could not get extra library folders: Parsing error.`
Application just displays "Parsing error."
![image](https://user-images.githubusercontent.com/96347680/146648349-00678626-e1bc-497f-9e73-aba35649001c.png)

0.9.2 experimental:
    Could not get extra library folders: Parsing error.
    Warning. Version mismatch: [0, 9, 2] != [0, 9, 0]
    thread '<unnamed>' panicked at 'not implemented: entity 0', bin-format\src\format.rs:272:22
    note: run with "RUST_BACKTRACE=1" environment variable to display a backtrace

Application appears as normal.
![image](https://user-images.githubusercontent.com/96347680/146648546-96ea1688-412d-44e5-9fee-3b0100916f4c.png)

**Comment by titonix** [comment]
happens to me aswell

**Comment by metarmask** [comment]
Thank you for the report. This should be fixed in [the latest version](https://github.com/metarmask/teardown/releases/latest).
