### ISSUE TITLE
[Regression] Missing voxels and wrong palette indexes

### ISSUE THREAD

**Issue by TTFH** [metarmask/teardown#2]
In the last commit [df56134](https://github.com/metarmask/teardown/commit/df5613460bd63003227e1496c144c3b858c95f8d), a lot of vehicles and props are missing voxels or use wrong palette indexes.
For example the tank (hash wdE5F82fp5M) don't have seats (made of plastic), and use the indexes for grass for things made of plastic (you can check the material in game using GetShapeMaterialAtPosition()), and the indexes for dirt and rock instead of hard metal.
This tool worked fine generating vox files from props on Teardown 0.6.2 with commit [eba9f3a](https://github.com/metarmask/teardown/commit/eba9f3aa3d622b4114fe020a037ac76dffec9b68) .

Edit: I want to add that some indexes uses Metallic 100 when they are not so shiny in game, this used to happen before too.

**Comment by metarmask** [comment]
I've mostly fixed this issue. For some shapes, which weren't created entirely in MagicaVoxel to begin with, this can be impossible. Examples from Evertides include the ice cream truck and the Dark Moon billboard. Therefore I've added warnings to the console for when palette indices overflow.
