### ISSUE TITLE
Converter Compatibility for 0.9.2

### ISSUE THREAD

**Issue by meowmangt** [metarmask/teardown#20]
I tried about a lot of different folders to put it in but it just seemed to make up a non-existing path on my drive and saying that it didnt found the steam directory there. Also it sometimes does that Parsing Error.

EDIT: Still no update.

**Comment by metarmask** [comment]
In the latest update it should allow you to enter a path manually in case it has a problem finding paths automatically. The path you launch it from should not have any effect.
