### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by 1AGameMaster** [metarmask/teardown#22]
Every time I try it it says:
"ParseError { kind: NotUTF8, phantom: PhantomData }

Backtrace:
0: <unknown>
1: <unknown>
2: <unknown>
3: <unknown>
4: <unknown>
5: <unknown>
6: <unknown>
7: <unknown>
8: BaseThreadInitThunk
9: RtlUserThreadStart"
Please fix this.

And sometimes that:
ParseError { kind: NoReprIntMatch(0), phantom: PhantomData }

Backtrace:
0: <unknown>
1: <unknown>
2: <unknown>
3: <unknown>
4: <unknown>
5: <unknown>
6: <unknown>
7: <unknown>
8: BaseThreadInitThunk
9: RtlUserThreadStart

**Comment by 1AGameMaster** [comment]
the blank is "<unknown>"

**Comment by metarmask** [comment]
Thanks for the report. [Here is the fixed version.](https://github.com/metarmask/teardown/releases) I should just change the message to always say "The tool doesn't work on this new version of Teardown" because that's pretty much always what the errors mean.
