### ISSUE TITLE
Wrong Metallic value for some materials

### ISSUE THREAD

**Issue by metarmask** [metarmask/teardown#3]
> Some indices use Metallic 100 when they are not so shiny in game

-- @TTFH

Unknown which levels/palettes this occurs on.

**Comment by TTFH** [comment]
It occurs on the side of the Gauss-Seidel B50 [lGsXWNhimo4.vox](https://filebin.net/apvpl73yj2aul7qz/lGsXWNhimo4.vox) on index 123, 127 and 130, in the Autogyro _aXQ0wDPbzXY.vox_ in index 122 and 123, as well in the propane semi-trailer.

**Other bugs:**
Emission and power values are always zero in lights.
Front, brake and reverse lights on vehicles don't uses the right indexes (it used to work before)
No top speed for vehicles in the xml

**Comment by metarmask** [comment]
Thanks for the report. I would appreciate it if you could submit the other bugs individually.

**Comment by metarmask** [comment]
Turns out it is impossible to perfectly translate all materials to MagicaVoxel. Metal in MagicaVoxel gets turned into shinyness _and_ reflectivity. These can be set separately using a voxbox. I have added warnings for this. If this issue was not caused by that, then I'm pretty sure this should be solved. Can you check? Make sure to delete the old .vox files.

**Comment by TTFH** [comment]
For emit materials I think it may be a better idea to set power to 3 and emission to half the current value (50 instead of 100).
Materials with roughtness 100 should be diffuse.
Materials should only have a value of metallic bigger than zero if roughtness is zero, in other cases you may want to reduce the roughtness value instead.

**Comment by metarmask** [comment]
> Materials with roughness 100 should be diffuse.

I don't know. I prefer metal because it's only one click to change the roughness. And roughness 100 with IOR 1 is the same as diffuse.

> Materials should only have a value of metallic bigger than zero if roughness is zero, in other cases you may want to reduce the roughness value instead.

That's not accurate to how the game translates the values back. I added tests based on a .vox file I made with all kinds of combinations of 0, 50 and 100 of metallic and roughness.

**Comment by metarmask** [comment]
There are two buttons for downloading MagicaVoxel. Version 0.99.4 has the specular option. The newer version doesn't have property and doesn't save it. This causes the game to use the same value for metalness and reflectivity. That's not "shinyness and reflectivity" like I said before - turns out the order in bin-format was wrong, perhaps because the voxbox pbr description was wrong before.
