### ISSUE TITLE
Wrong values for emission and power in emit materials

### ISSUE THREAD

**Issue by TTFH** [metarmask/teardown#4]
Indexes in the palette with emit materials have a value of zero in emission (range 0..100) and a value of one in power (range 1..5). Instead of the correct values that make those voxels emit light in game.

**Comment by metarmask** [comment]
Flux and emission get turned into a single value. For now I'm setting flux to 2 and adjusting the emission to at least get the same value when converting back to the game again.

**Comment by metarmask** [comment]
> For emit materials I think it may be a better idea to set power to 3 and emission to half the current value (50 instead of 100).

Actually, I realized my approach doesn't actually work (at least not when open and then save the file) because emission is corrected if above 100. The formula for calculating the emission in the game is: `vox_emission/100 * 10^power`. So I should be able to set both by looking at the range.
