### ISSUE TITLE
Wrong values for color, angle and penumbra on lights

### ISSUE THREAD

**Issue by TTFH** [metarmask/teardown#7]
Some attributes in the lights have wrong values when converted.
For example, if you create a map that have lights, make a quick-save and convert that map, some values are different to the originals. For example:
- [x] A light with color RGB(1, 0.5, 0) is converted to RGB(1, 0.2176, 0).
- [x] Angle values are also wrong: 45º is converted to 52.9º and 60º is converted to 50º.
- [x] Penumbra values are totally out of range, a penumbra of 5 is converted to 54 and a penumbra of 10 is converted to 62.
- [x] Light position is slightly out of place.
- [x] A map with 3 lights have 4 lights after being converted.

[Example map](https://ufile.io/z2tmpz69)
The parsing of the binary files makes sense according to this:
https://github.com/nxhu64/TDU/blob/main/TDU/Entities.h#L124
So, I'm not sere where the problem is.

In the binary files, at the location for angle you can find a float32 = 5E 83 6C 3F = 0.9239 rad = 52.9º that is different to 45º, maybe the angle is stored at a different location?

**Comment by metarmask** [comment]
The extra light is actually the player flashlight. Maybe it should be hidden and/or labeled.

For vehicles at least, the lights seem be rotated 180 degrees, which makes it look like the front lights are somewhat in the right place at the back.

Oh, the penumbra is supposed to be small? Then the editor penumbra is probably (binary penumbra - angle)  I think I'll look into all this tomorrow.
