### ISSUE TITLE
Wrong rotation and limits on joints

### ISSUE THREAD

**Issue by TTFH** [metarmask/teardown#8]
Rotation on hinge and prismatic joints are not right, for example the joints on the front loader in Marina have a rotation of (-60 0 0) instead of (0 -20 0), other joints are rotated 90º from the right position.
Limits on prismatic joints are wrong, those limits should be in meters. Maybe you are converting the values to degrees?

**Comment by metarmask** [comment]
Thanks, yes, I was converting them to degrees.

It appears the rotation on the joint is only for defining the relationship between the rotations of the connected bodies. I can rotate the joint on the crane arm like the arm itself is rotated, so it looks like the limits would change, but it behaves identically.

### Mystery triplets
They change _very_ slightly when changing the rotation on the same circle, like I described above. They change as I change the X rotation (to the sides of the vehicle) on the crane. I haven't confirmed they are actually related to the shapes.
|editor x|shape|a|b|c|
|-|-|-|-|-|
|0.00|0|+1.00|+0.00|+0.00|
|10.0|0|+0.94|+0.17|+0.30|
|0.00|1|+1.00|+0.00|+0.00|
|10.0|1|+0.94|-0.34|+0.06|
### Rotations of connected shapes
|shape|x|y|z|
|-|-|-|-|
|0|+10.0|-180|+0.00|
|1|-90.0|-180|+0.00|
