### ISSUE TITLE
No steer, drive or travel on wheels

### ISSUE THREAD

**Issue by TTFH** [metarmask/teardown#9]
This is where those parameters are located on the binary files:
https://github.com/nxhu64/TDU/blob/main/TDU/Entities.h#L192

Drive is in range 0.0 - 1.0
Steer is in range -1.0 - 1.0
Travel are two values

**Comment by metarmask** [comment]
It should be noted that those structs aren't what is directly saved. They're still helpful though.
> each object can choose freely what to save, and might leave out cached state or temporary acceleration structures.

-- [Dennis Gustafsson](https://blog.tuxedolabs.com/2020/11/18/teardown-quicksave.html)

Another example are booleans which are saved with one byte in the save but four bytes in memory.
